### ISSUE TITLE
Cannot fully read out data pages if data contains a 0.

### ISSUE THREAD

**Issue by ChrisSchaetzle** [alttch/owfs-rs#1]
If I try to read out a data page of 32 bytes it is only partially read out due to a false nullterminator.
The data contains zeroes.  The first one is interpreted as a string terminator.

This was going to be my first little rust project trying to learn the language :-).

**Comment by divi255** [comment]
thanks for reporting. I'm going to look on that

**Comment by divi255** [comment]
looking on this. owfs returns bulk data separated with commas. can you please give any example where you have faced with null terminator in return payloads?

**Comment by ChrisSchaetzle** [comment]
OK. Here is the debug out:

[src/main.rs:21:17] d.get("pages/page.2").unwrap().as_bytes() = [
    65,
    69,
    58,
    102,
]

what I am expecting is:

0x41453A66000000001902D5060000000000000000000000000000000000008C3B

So I'm getting the first 4 bytes. The rest is being cut off.

When I debug into the `get` function the entire data is in the buffer `buf`.
Then there is the line:
`let data = CStr::from_ptr(buf);`
here the data is cut off at the first 0x00 byte.

Here is my test function Just for reference:
```rust
fn main() {
    unsafe {
        owfs::init("localhost:4304").unwrap();
        let devices = owfs::scan(owfs::ScanOptions::default()).unwrap();
        for d in devices {

            let ow_device = d.get("type").unwrap();
            if ow_device.contains("DS2431") {
                dbg!(d.get("pages/page.2").unwrap().as_bytes());
        }
        owfs::finish();
    }
}
```

**Comment by divi255** [comment]
oh I understand. actually I have never dug 1-wire exports so deep. I've added "get_bytes/set_bytes" methods in 0.0.9, with them you can always get the whole buffer and parse it your way.
